import * as THREE from 'three';
import { throwVelocity } from './grab.js';

const clamp = THREE.MathUtils.clamp;
export function setupDevTools(api) {
  const style = document.createElement('style');
  style.textContent = `.dev-panel{position:fixed;z-index:8;right:20px;top:90px;width:296px;max-height:calc(100vh - 120px);overflow:auto;background:#fffdf2f5;backdrop-filter:blur(20px);border:1px solid #fff;border-radius:17px;box-shadow:0 8px 40px #25413635;padding:17px;color:#344c3b;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.dev-panel[hidden]{display:none}.dev-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:15px}.dev-heading b{font-family:Georgia,serif;font-size:23px;font-weight:400}.dev-heading button{font-size:22px}.dev-tabs{display:flex;gap:4px;border-bottom:1px solid #d9dfcd;margin-bottom:16px;padding-bottom:8px}.dev-tabs button{font-size:10px;padding:8px 11px;border-radius:7px}.dev-tabs button.active{background:#355747;color:#fff9e9}.dev-section[hidden]{display:none}.dev-note{font-size:10px;color:#86917d;line-height:1.5;margin:9px 0 13px}.dev-tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px}.dev-tool-grid button,.dev-action{background:#eceddf;border-radius:8px;padding:10px;text-align:left;font-size:10px}.dev-tool-grid button.active{background:#b86f4e;color:#fffaf0}.dev-actions{display:flex;flex-wrap:wrap;gap:6px;margin-top:12px}.dev-action.danger{background:#eed8c9;color:#8c5037}.dev-range{display:block;margin:15px 0}.dev-range>span{display:flex;justify-content:space-between;font-size:9px;margin-bottom:9px;letter-spacing:.5px}.dev-range output{color:#a06748;font-variant-numeric:tabular-nums}.dev-range input[type=range]{width:100%;accent-color:#6a8660;height:4px}.dev-inspector{display:grid;grid-template-columns:1fr 1fr;gap:9px 13px;font-size:10px}.dev-inspector span{color:#8a967f}.dev-inspector b{text-align:right;font-weight:550;font-variant-numeric:tabular-nums}.dev-check{display:flex;gap:8px;align-items:center;font-size:10px;margin:15px 0}.dev-check input{accent-color:#69865e}.dev-power-status{font-size:9px;line-height:1.5;padding:10px 11px;border-radius:8px;background:#e7e9d9;margin-bottom:10px}.dev-select{font-size:10px;border:1px solid #d4dcc7;background:#fffdf2;padding:8px;border-radius:6px;width:100%;color:#526747}@media(max-width:700px){.dev-panel{right:12px;top:77px;width:265px;max-height:calc(100vh - 100px)}}`;
  document.head.append(style);
  const openButton = document.createElement('button');
  openButton.id='dev-tools';openButton.title='Developer tools and god powers (D)';openButton.setAttribute('aria-label','Developer tools and god powers');
  openButton.innerHTML='<svg viewBox="0 0 24 24"><path d="M14 6a5 5 0 0 0-6 6L3 17l4 4 5-5a5 5 0 0 0 6-6l-3 3-4-4z"/></svg>';
  document.querySelector('.footer-actions').prepend(openButton);
  const grabButton=document.createElement('button');
  grabButton.id='grab-cars';grabButton.className='grab-cars';grabButton.title='Pick up, drop, and throw (G)';grabButton.setAttribute('aria-pressed','false');
  grabButton.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12V8a1.5 1.5 0 0 1 3 0v3-6a1.5 1.5 0 0 1 3 0v6-7a1.5 1.5 0 0 1 3 0v7-5a1.5 1.5 0 0 1 3 0v7l2-2a1.5 1.5 0 0 1 2 2l-3 6a4 4 0 0 1-4 3h-4a4 4 0 0 1-4-3l-3-5a1.5 1.5 0 0 1 2-2l2 2"/></svg><span>Grab & throw</span>';
  document.querySelector('.footer-actions').prepend(grabButton);
  const grabMenu=document.createElement('aside');grabMenu.className='grab-menu glass';grabMenu.hidden=true;grabMenu.setAttribute('aria-label','Grab and throw controls');
  grabMenu.innerHTML='<div class="grab-heading"><b>Pick up your world</b><button aria-label="Close grab controls">×</button></div><div class="grab-modes" role="group" aria-label="What to grab"><button data-grab="car" aria-pressed="true">Cars</button><button data-grab="person" aria-pressed="false">People</button><button data-grab="prop" aria-pressed="false">Buildings & trees</button></div><p id="grab-help">Hold a car to lift it. Move, then release gently to drop or flick to throw.</p><button class="grab-camera">Return to camera</button>';
  document.body.append(grabMenu);let grabKind='car';
  const panel=document.createElement('aside');panel.className='dev-panel';panel.hidden=true;panel.setAttribute('aria-label','Developer tools');
  panel.innerHTML=`<div class="dev-heading"><b>The control room</b><button aria-label="Close developer tools">×</button></div><div class="dev-tabs"><button data-tab="powers" class="active">God powers</button><button data-tab="physics">Physics</button><button data-tab="inspect">Inspect</button></div>
  <section class="dev-section" data-section="powers"><div class="dev-power-status">Choose a power, then click the world. Changes persist until you repair or restore it.</div><div class="dev-tool-grid"><button data-tool="explore" class="active">◉ Explore</button><button data-tool="meteor">☄ Drop a meteor</button><button data-tool="shockwave">◎ Shockwave</button><button data-tool="raise">↟ Raise terrain</button><button data-tool="lower">↡ Lower terrain</button><button data-tool="repair">✧ Repair ground</button><button data-tool="throw">↗ Grab & throw</button></div><label class="dev-range"><span>BRUSH RADIUS <output id="brush-output">4 m</output></span><input id="brush-radius" aria-label="Brush radius" type="range" min="2" max="12" step="0.5" value="4"></label><div class="dev-actions"><button class="dev-action" data-action="boost">Boost racer</button><button class="dev-action" data-action="spin">Spin racer</button><button class="dev-action" data-action="repair-car">Repair racer</button><button class="dev-action danger" data-action="restore">Restore whole world</button></div><p class="dev-note">Use Grab & throw to choose cars, adult townspeople, buildings, or trees. Meteors fall under gravity. Shockwaves push cars and break nearby scenery.</p></section>
  <section class="dev-section" data-section="physics"><div id="physics-sliders"></div><label class="dev-range"><span>TIME SCALE <output id="dev-time-output">1×</output></span><input id="dev-time" aria-label="Simulation time scale" type="range" min="0.1" max="3" step="0.1" value="1"></label><div class="dev-actions"><button class="dev-action" data-action="pause">Freeze / resume</button><button class="dev-action" data-action="default-physics">Reset physics</button></div><p class="dev-note">Tire friction, impact response and terrain damage share this simulation. Very low grip can keep drivers from completing a lap.</p></section>
  <section class="dev-section" data-section="inspect"><label class="dev-check"><input id="debug-bodies" type="checkbox">Collision bodies & velocity vectors</label><div class="dev-inspector" id="dev-inspector"></div><p class="dev-note">Vehicle bodies use planar tire forces and rigid body impulses. Vehicle height follows the deformed ground. Debris and meteors use gravity.</p></section>`;
  document.body.append(panel);panel.querySelectorAll('[data-section]').forEach(s=>s.hidden=s.dataset.section!=='powers');
  const configs=[['gravity','Gravity',1,20,.1,9.81,'m/s²'],['grip','Tire grip',.35,2.4,.05,1,'×'],['restitution','Impact bounce',0,.7,.02,.12,''],['damageScale','Damage multiplier',0,3,.1,1,'×'],['enginePower','Engine power',.4,2.5,.1,1,'×']];
  const controls={};for(const [key,name,min,max,step,value,unit] of configs){const label=document.createElement('label');label.className='dev-range';label.innerHTML=`<span>${name.toUpperCase()} <output>${value} ${unit}</output></span><input type="range" aria-label="${name}" min="${min}" max="${max}" step="${step}" value="${value}">`;const input=label.querySelector('input');controls[key]=input;input.oninput=()=>{label.querySelector('output').textContent=`${Number(input.value).toFixed(key==='gravity'?1:2)} ${unit}`;api.getSim().configurePhysics({[key]:Number(input.value)})};panel.querySelector('#physics-sliders').append(label)}
  let tool='explore',radius=4,active=false,dragging=false,held=null,heldHistory=[],heldHeight=0,heldOffset={x:0,z:0},lastBrush=0,meteors=[],debug=null,worldRef=null,lastInspector=0;
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0),hitPoint=new THREE.Vector3();
  const dragPlane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
  const meteorGeometry=new THREE.IcosahedronGeometry(.7,1),meteorMaterial=new THREE.MeshStandardMaterial({color:0x685850,roughness:.9});
  const debugMaterial=new THREE.LineBasicMaterial({color:0xc78552,transparent:true,opacity:.8,depthTest:false});
  const vehicleWire=new THREE.EdgesGeometry(new THREE.BoxGeometry(1.08,.5,1.95));
  const velocityGeometry=new THREE.BufferGeometry();velocityGeometry.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,0,0,0],3));
  function toggle(){panel.hidden=!panel.hidden;openButton.classList.toggle('active',!panel.hidden);if(panel.hidden)setTool('explore')}
  openButton.onclick=toggle;panel.querySelector('.dev-heading button').onclick=toggle;
  function setTool(next){if(next!==tool&&held!==null)release(undefined,false);tool=next;active=tool!=='explore';if(tool==='throw'&&api.getMode()!=='orbit')api.setMode('orbit');api.getControls().enabled=!active&&api.getMode()==='orbit';api.getCanvas().style.cursor=tool==='throw'?'grab':active?'crosshair':'';grabButton.classList.toggle('active',tool==='throw');grabButton.setAttribute('aria-pressed',String(tool==='throw'));grabButton.querySelector('span').textContent=tool==='throw'?'Grabbing':'Grab & throw';grabMenu.hidden=tool!=='throw';panel.querySelectorAll('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));panel.querySelector('.dev-power-status').textContent=tool==='throw'?'Choose cars, people, or scenery in the grab controls. Hold to lift; release to drop or flick to throw.':active?`${panel.querySelector(`[data-tool="${tool}"]`).textContent.replace(/^[^a-z]+/i,'')} selected. Click the world.`:'Choose a power, then click the world. Changes persist until you repair or restore it.'}
  grabButton.onclick=()=>{setTool(tool==='throw'?'explore':'throw');};
  grabMenu.querySelector('.grab-heading button').onclick=()=>setTool('explore');grabMenu.querySelector('.grab-camera').onclick=()=>setTool('explore');
  grabMenu.querySelectorAll('[data-grab]').forEach(button=>button.onclick=()=>{if(held!==null)release(undefined,false);grabKind=button.dataset.grab;grabMenu.querySelectorAll('[data-grab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));grabMenu.querySelector('#grab-help').textContent=grabKind==='person'?'Hold an adult to lift them. Release to drop or flick to throw. Children stay with their families and run from danger.':grabKind==='prop'?'Hold a building, tree, rock, or landmark to lift it. Hard landings and collisions break it.':'Hold a car to lift it. Move, then release gently to drop or flick to throw.';});
  panel.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{panel.querySelectorAll('[data-tab]').forEach(v=>v.classList.toggle('active',v===b));panel.querySelectorAll('[data-section]').forEach(s=>s.hidden=s.dataset.section!==b.dataset.tab)});
  panel.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));panel.querySelector('#brush-radius').oninput=e=>{radius=Number(e.target.value);panel.querySelector('#brush-output').textContent=radius+' m'};
  panel.querySelector('#dev-time').oninput=e=>{const v=Number(e.target.value);api.setSpeed(v);panel.querySelector('#dev-time-output').textContent=v+'×'};
  panel.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const sim=api.getSim(),c=sim.cars[api.getSelected()];switch(b.dataset.action){case'boost':sim.applyImpulse(c.id,{x:Math.sin(c.heading)*(c.mass||700)*12,z:Math.cos(c.heading)*(c.mass||700)*12});break;case'spin':sim.applyImpulse(c.id,{x:Math.cos(c.heading)*(c.mass||700)*6,z:-Math.sin(c.heading)*(c.mass||700)*6},{x:c.x+Math.sin(c.heading)*.8,z:c.z+Math.cos(c.heading)*.8});break;case'repair-car':sim.repairCar(c.id);api.toast(`${c.name} is freshly repaired`);break;case'restore':api.restoreWorld();setTool('explore');api.toast('The little world is whole again');break;case'pause':api.togglePause();break;case'default-physics':for(const [key,,,,,value,unit] of configs){controls[key].value=value;controls[key].parentElement.querySelector('output').textContent=value+' '+unit}sim.configurePhysics(Object.fromEntries(configs.map(c=>[c[0],c[5]])));break}});
  function pointAt(e){const rect=api.getCanvas().getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,api.getCamera());if(held!==null)return raycaster.ray.intersectPlane(dragPlane,hitPoint)?hitPoint.clone():null;const terrain=api.getTerrain();const hit=raycaster.intersectObject(terrain.mesh,false)[0];if(hit)return hit.point.clone();return raycaster.ray.intersectPlane(ground,hitPoint)?hitPoint.clone():null}
  function shockwave(x,z,energy=1,r=radius*2.2){api.getPeople().blast(x,z,r,energy);const sim=api.getSim();for(const c of sim.cars){const dx=c.x-x,dz=c.z-z,d=Math.hypot(dx,dz);if(d>r)continue;const force=(c.mass||700)*energy*13*(1-d/r),inv=1/Math.max(d,.1);sim.applyImpulse(c.id,{x:dx*inv*force,z:dz*inv*force,y:force*.3})}api.damageWorld(x,z,r,energy*18000);api.getTerrain().impact(x,z,energy,radius);api.refreshTerrain();}
  function applyTool(p){const terrain=api.getTerrain();api.reactPeople(p.x,p.z,tool==='meteor'?23:radius+8,tool==='repair'?'repair':tool);if(tool==='meteor'){if(meteors.length>=12){meteors[0].mesh.removeFromParent();meteors.shift()}const ball=new THREE.Mesh(meteorGeometry,meteorMaterial);ball.position.set(p.x,28,p.z);ball.castShadow=true;api.getWorld().add(ball);meteors.push({mesh:ball,vy:0,life:0})}else if(tool==='shockwave')shockwave(p.x,p.z,1.1);else if(tool==='raise')terrain.sculpt(p.x,p.z,.45,radius);else if(tool==='lower')terrain.sculpt(p.x,p.z,-.45,radius);else if(tool==='repair')terrain.repairAt(p.x,p.z,radius);api.refreshTerrain()}
  const canvas=api.getCanvas();
  function heldBody(){return held?.kind==='car'?api.getSim().cars[held.id]:held?.kind==='person'?api.getPeople().crowd.people[held.id]:api.getScenery().colliders.find(c=>c.id===held?.id);}
  canvas.addEventListener('pointerdown',e=>{
    if(!active||e.button!==0)return;e.preventDefault();e.stopImmediatePropagation();const p=pointAt(e);if(!p)return;
    if(tool==='throw'){
      let body=null;
      if(grabKind==='car'){const hit=raycaster.intersectObjects(api.getCarMeshes(),false)[0];if(hit){body=api.getSim().cars[hit.object.userData.carId];held={kind:'car',id:body.id};}}
      else if(grabKind==='person'){const hit=raycaster.intersectObjects(api.getPeople().targets,false)[0];if(hit){body=api.getPeople().pick(hit);if(body?.child){api.toast('Children stay with their families. Choose an adult to grab.');return;}if(body)held={kind:'person',id:body.id};}}
      else {for(const hit of raycaster.intersectObject(api.getWorld(),true)){body=api.getScenery().pickProp(hit);if(body){held={kind:'prop',id:body.id};break;}}}
      if(!body){api.toast(grabKind==='car'?'Click a car to pick it up':grabKind==='person'?'Zoom in and click an adult townsperson':'Click a building, tree, rock, or landmark');return;}
      const base=held.kind==='person'&&!body.airborne?api.getTerrain().heightAt(body.x,body.z):body.y;
      heldHeight=base+(held.kind==='prop'?3.5:1.8);dragPlane.constant=-heldHeight;const liftedPoint=pointAt(e);heldOffset={x:body.x-(liftedPoint?.x??body.x),z:body.z-(liftedPoint?.z??body.z)};
      if(held.kind==='car'){body.held=true;body.airborne=true;body.y=heldHeight;body.vx=body.vy=body.vz=0;api.selectCar(held.id);}
      else if(held.kind==='person')api.getPeople().lift(held.id,heldHeight);
      else api.getScenery().liftProp(held.id,heldHeight);
      heldHistory=[{x:body.x,z:body.z,t:performance.now()}];canvas.style.cursor='grabbing';api.reactPeople(body.x,body.z,9,'grab');
    }else{applyTool(p);lastBrush=performance.now();}
    dragging=true;canvas.setPointerCapture(e.pointerId);
  },true);
  canvas.addEventListener('pointermove',e=>{if(!active||!dragging)return;e.preventDefault();e.stopImmediatePropagation();const p=pointAt(e);if(!p)return;if(held!==null){
    const body=heldBody();if(!body)return;const x=clamp(p.x+heldOffset.x,-100,100),z=clamp(p.z+heldOffset.z,-80,80);
    if(held.kind==='car'){api.getSim().teleportCar(held.id,x,z,body.heading);body.held=true;body.airborne=true;body.y=heldHeight;}
    else if(held.kind==='person')api.getPeople().move(held.id,x,z,heldHeight);else api.getScenery().moveProp(held.id,x,z,heldHeight);
    heldHistory.push({x,z,t:performance.now()});heldHistory=heldHistory.filter(v=>v.t>performance.now()-200);api.reactPeople(x,z,7,'grab');
  }else if(['raise','lower','repair'].includes(tool)&&performance.now()-lastBrush>70){applyTool(p);lastBrush=performance.now();}},true);
  function release(e,toss=true){
    if(!active&&held===null)return;e?.stopImmediatePropagation?.();dragging=false;
    if(held!==null){const body=heldBody(),velocity=toss?throwVelocity(heldHistory,performance.now()):{x:0,z:0,y:0};
      if(body){if(held.kind==='car'){body.held=false;body.airborne=true;api.getSim().applyImpulse(held.id,{x:velocity.x*body.mass,z:velocity.z*body.mass,y:velocity.y*body.mass});}else if(held.kind==='person')api.getPeople().release(held.id,velocity);else api.getScenery().releaseProp(held.id,velocity);
      api.reactPeople(body.x,body.z,11,'grab');const name=held.kind==='car'?body.name:held.kind==='person'?'Townsperson':body.kind==='building'?'Building':body.kind;api.toast(Math.hypot(velocity.x,velocity.z)>1?`${name} takes flight!`:`${name} dropped`);}
      held=null;heldHistory=[];canvas.style.cursor=tool==='throw'?'grab':'';
    }
    if(e&&canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);
  }
  canvas.addEventListener('pointerup',e=>release(e),true);canvas.addEventListener('pointercancel',e=>release(e,false),true);canvas.addEventListener('lostpointercapture',()=>{if(held!==null)release(undefined,false)});addEventListener('blur',()=>release(undefined,false));
  addEventListener('keydown',e=>{if(e.key==='Escape'&&active){setTool('explore');panel.hidden=true;openButton.classList.remove('active');return;}if(e.target.closest('input,select,textarea,button,[contenteditable=true]'))return;if(e.key==='d'||e.key==='D')toggle();if(e.key==='g'||e.key==='G')grabButton.click();});
  function buildDebug(){if(debug)debug.removeFromParent();debug=new THREE.Group();api.getWorld().add(debug);for(const c of api.getSim().cars){const body=new THREE.LineSegments(vehicleWire,debugMaterial);body.userData.car=c.id;debug.add(body);const v=new THREE.Line(velocityGeometry.clone(),new THREE.LineBasicMaterial({color:0x64dca8,depthTest:false}));v.userData.velocity=c.id;debug.add(v)}for(const c of api.getScenery().colliders){const pts=Array.from({length:33},(_,i)=>new THREE.Vector3(Math.cos(i/32*Math.PI*2)*c.radius,.16,Math.sin(i/32*Math.PI*2)*c.radius));const wire=new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),debugMaterial);wire.position.set(c.x,0,c.z);wire.userData.collider=c;debug.add(wire)}}
  function update(dt){const w=api.getWorld();if(w!==worldRef){worldRef=w;meteors=[];held=null;debug=null;buildDebug();for(const [key,input] of Object.entries(controls)){input.value=api.getSim().physics[key];const config=configs.find(c=>c[0]===key);input.parentElement.querySelector('output').textContent=api.getSim().physics[key]+' '+config[6]}api.getControls().enabled=!active&&api.getMode()==='orbit'}
    const gravity=api.getSim().physics.gravity;for(const m of meteors){m.vy-=gravity*dt;m.mesh.position.y+=m.vy*dt;m.mesh.rotation.x+=dt;m.mesh.rotation.z+=dt*.8;const h=api.surfaceHeightAt(m.mesh.position.x,m.mesh.position.z);if(m.mesh.position.y<=h+.7){shockwave(m.mesh.position.x,m.mesh.position.z,Math.min(2,Math.abs(m.vy)/18));m.life=-1;m.mesh.removeFromParent()}}meteors=meteors.filter(m=>m.life!==-1);
    const debugOn=panel.querySelector('#debug-bodies').checked;debug.visible=debugOn;if(debugOn){for(const child of debug.children){if(child.userData.car!==undefined){const c=api.getSim().cars[child.userData.car];child.position.set(c.x,c.y+.3,c.z);child.rotation.y=c.heading}else if(child.userData.velocity!==undefined){const c=api.getSim().cars[child.userData.velocity],a=child.geometry.attributes.position;a.setXYZ(0,c.x,c.y+.5,c.z);a.setXYZ(1,c.x+c.vx*.3,c.y+.5,c.z+c.vz*.3);a.needsUpdate=true}else if(child.userData.collider)child.visible=child.userData.collider.health>0}}
    if(!panel.hidden&&performance.now()-lastInspector>150){lastInspector=performance.now();const c=api.getSim().cars[api.getSelected()],f=n=>Number.isFinite(n)?n.toFixed(2):'0.00';const entries=[['Town population',api.getPeople().stats.population],['Panicking',api.getPeople().stats.panicking],['Driver',c.name],['Speed',f(c.speed)+' m/s'],['Velocity X',f(c.vx)],['Velocity Z',f(c.vz)],['Yaw rate',f(c.yawRate)+' rad/s'],['Steering',f(c.steering)+' rad'],['Throttle',Math.round(c.throttle*100)+'%'],['Brake',Math.round(c.brake*100)+'%'],['Tire slip',f(c.slip)],['Surface',c.surface],['Damage',Math.round(c.damage.total*100)+'%'],['Solid props',api.getScenery().colliders.filter(v=>v.health>0).length]];panel.querySelector('#dev-inspector').innerHTML=entries.map(([k,v])=>`<span>${k}</span><b>${v}</b>`).join('')}
  }
  return {update,active:()=>active,panel,restorePhysics:()=>{for(const input of Object.values(controls))input.oninput()}};
}
