import * as THREE from 'three';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
/** Depth-averaged, conservative 1D channel water with hydrostatic reconstruction. */
export class ChannelFlow{
 constructor({count=80,length=72,bedAt=s=>-.9-.6*s,closed=false}={}){this.count=count;this.length=length;this.dx=length/count;this.bedAt=bedAt;this.closed=closed;this.clock=0;this.h=Float64Array.from({length:count},(_,i)=>Math.max(.01,.09-bedAt((i+.5)/count)));this.q=new Float64Array(count);this.bed=new Float64Array(count);this.refreshBed();}
 refreshBed(){for(let i=0;i<this.count;i++)this.bed[i]=this.bedAt((i+.5)/this.count);}
 update(dt){if(!Number.isFinite(dt)||dt<=0)return;let remaining=Math.min(dt,.5);this.refreshBed();while(remaining>1e-7){let fastest=1;for(let i=0;i<this.count;i++)fastest=Math.max(fastest,Math.abs(this.q[i]/Math.max(.01,this.h[i]))+Math.sqrt(9.81*this.h[i]));const step=Math.min(remaining,.24*this.dx/fastest);this.step(step);remaining-=step;this.clock+=step;}}
 step(dt){const N=this.count,g=9.81,fluxH=new Float64Array(N+1),leftP=new Float64Array(N+1),rightP=new Float64Array(N+1);for(let j=0;j<=N;j++){const l=Math.max(0,j-1),r=Math.min(N-1,j);let hl=this.h[l],hr=this.h[r],ql=this.q[l],qr=this.q[r],bl=this.bed[l],br=this.bed[r];if(j===0){if(this.closed)ql=-qr;else{hl=Math.max(.01,.09-bl);ql=.45;}}if(j===N&&this.closed)qr=-ql;const top=Math.max(bl,br),hL=Math.max(0,hl+bl-top),hR=Math.max(0,hr+br-top),uL=ql/Math.max(.01,hl),uR=qr/Math.max(.01,hr),qL=hL*uL,qR=hR*uR,a=Math.max(Math.abs(uL)+Math.sqrt(g*hL),Math.abs(uR)+Math.sqrt(g*hR));fluxH[j]=(qL+qR-a*(hR-hL))*.5;const f=(qL*uL+.5*g*hL*hL+qR*uR+.5*g*hR*hR-a*(qR-qL))*.5;leftP[j]=f+.5*g*(hl*hl-hL*hL);rightP[j]=f+.5*g*(hr*hr-hR*hR);}
 for(let i=0;i<N;i++){this.h[i]=Math.max(0,this.h[i]-dt/this.dx*(fluxH[i+1]-fluxH[i]));this.q[i]-=dt/this.dx*(leftP[i+1]-rightP[i]);this.q[i]/=1+dt*.22*Math.abs(this.q[i])/Math.max(.04,this.h[i]**2);if(this.h[i]<.001)this.q[i]=0;}
 }
 sample(s){const i=clamp(Math.floor(s*this.count),0,this.count-1);return{depth:this.h[i],bed:this.bed[i],surface:this.bed[i]+this.h[i],speed:this.q[i]/Math.max(.01,this.h[i])};}
 get volume(){return this.h.reduce((s,h)=>s+h,0)*this.dx;}
 exportState(){return{clock:this.clock,h:[...this.h],q:[...this.q]};}
 restoreState(s){if(!s||s.h?.length!==this.count||s.q?.length!==this.count||!s.h.every(v=>Number.isFinite(v)&&v>=0&&v<40)||!s.q.every(v=>Number.isFinite(v)&&Math.abs(v)<200))return false;this.h.set(s.h);this.q.set(s.q);this.clock=Number.isFinite(s.clock)?Math.max(0,s.clock):0;this.refreshBed();return true;}
}
export function floatForce(body,water,dt,gravity=9.81,draft=.2,buoyancy=1){if(!water||dt<=0||body.y>water.surface+.3)return false;const submerged=clamp((water.surface-body.y)/draft,0,2);body.vy+=gravity*submerged*buoyancy*dt;body.vy*=Math.exp(-dt*3*submerged);const blend=1-Math.exp(-dt*1.4*submerged);body.vx+=(water.vx-body.vx)*blend;body.vz+=(water.vz-body.vz)*blend;return submerged>0;}
export function createWater({group,terrain,river=false,color=0x6eafb4}){
 const curve=new THREE.CatmullRomCurve3([[12,-40],[24,-28],[33,-16],[45,-12],[64,-5]].map(([x,z])=>new THREE.Vector3(x,0,z)));const N=80,points=Array.from({length:N+1},(_,i)=>curve.getPointAt(i/N)),tangents=points.map((_,i)=>curve.getTangentAt(i/N));let clock=0;
 const bedAt=s=>{const p=curve.getPointAt(s);return -.9-.6*s+terrain.heightAt(p.x,p.z);};let flow=river?new ChannelFlow({count:N,length:curve.getLength(),bedAt}):null;const initial=flow?.exportState();let mesh,foam,dummy=new THREE.Object3D();const particles=Array.from({length:70},(_,i)=>({s:(i*.618)%1,offset:(i%5-2)*.57}));
 if(flow){const pos=new Float32Array((N+1)*6),ind=[];for(let i=0;i<N;i++){const j=i*2;ind.push(j,j+2,j+1,j+1,j+2,j+3);}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(pos,3));geometry.setIndex(ind);const mat=new THREE.MeshStandardMaterial({color,roughness:.32,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1,polygonOffsetUnits:-4});mesh=new THREE.Mesh(geometry,mat);mesh.name='Physical channel water';mesh.frustumCulled=false;group.add(mesh);foam=new THREE.InstancedMesh(new THREE.PlaneGeometry(.045,.72),new THREE.MeshBasicMaterial({color:0xe6f6ea,transparent:true,opacity:.5,side:THREE.DoubleSide,depthWrite:false}),particles.length);foam.frustumCulled=false;group.add(foam);}
 function channelAt(x,z){if(!flow)return null;let closest=Infinity,index=0;for(let i=0;i<points.length;i++){const d=Math.hypot(points[i].x-x,points[i].z-z);if(d<closest){closest=d;index=i;}}if(closest>2.3)return null;const s=flow.sample(index/N),t=tangents[index];return{...s,vx:t.x*s.speed,vz:t.z*s.speed};}
 function sample(x,z){const channel=channelAt(x,z);if(channel&&channel.depth>.02)return channel;if(terrain.contains(x,z))return null;const surface=-3+.07*Math.sin(x*.11+clock*1.04)+.04*Math.sin(z*.18-clock*1.33);return{surface,bed:-7,depth:surface+7,vx:.22+.08*Math.sin(clock*.4+z*.07),vz:.12*Math.cos(clock*.3+x*.06)};}
 function render(dt){if(!flow)return;const pos=mesh.geometry.attributes.position;for(let i=0;i<=N;i++){const p=points[i],t=tangents[i],s=flow.sample(i/N),y=s.depth>.025?s.surface:terrain.heightAt(p.x,p.z)+.014;for(let side=0;side<2;side++)pos.setXYZ(i*2+side,p.x+t.z*2.3*(side?1:-1),y,p.z-t.x*2.3*(side?1:-1));}pos.needsUpdate=true;mesh.geometry.computeVertexNormals();particles.forEach((a,i)=>{a.s=(a.s+Math.max(0,flow.sample(a.s).speed)*dt/flow.length)%1;const p=curve.getPointAt(a.s),t=curve.getTangentAt(a.s),water=flow.sample(a.s);dummy.position.set(p.x+t.z*a.offset,water.surface+.015,p.z-t.x*a.offset);dummy.rotation.set(-Math.PI/2,0,-Math.atan2(t.x,t.z));dummy.scale.setScalar(water.depth>.04?1:0);dummy.updateMatrix();foam.setMatrixAt(i,dummy.matrix);});foam.instanceMatrix.needsUpdate=true;}
 render(0);return{sample,flow,update:dt=>{if(dt<=0)return;clock+=dt;flow?.update(dt);render(dt);},reset:()=>{clock=0;if(flow)flow.restoreState(initial);render(0);},exportState:()=>({clock,channel:flow?.exportState()}),restoreState:s=>{if(Number.isFinite(s?.clock))clock=Math.max(0,s.clock);const ok=!flow||flow.restoreState(s?.channel);render(0);return ok;},get stats(){return{clock,channelCells:flow?.count||0,discharge:flow?flow.q.reduce((a,b)=>a+b,0)/N:0};}};
}
